import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { Logger } from '../utils/logger';
import { ConfigurationManager } from '../config/configurationManager';

/**
 * Manages the `last.rb` intermediate output file.
 * Responsible for locating, reading, and validating the Ruby output file
 * generated by Python script execution.
 */
export class OutputFileManager {
  /**
   * Get the path to the output file (last.rb).
   * Respects the `outputFile` configuration setting.
   */
  getOutputFilePath(): string {
    return ConfigurationManager.getOutputFile();
  }

  /**
   * Read the output file content after Python execution.
   * Returns the file content or null if the file doesn't exist or is empty.
   */
  async readOutputFile(): Promise<string | null> {
    const filePath = this.getOutputFilePath();

    try {
      if (!fs.existsSync(filePath)) {
        Logger.warn(`Output file not found: ${filePath}`);
        return null;
      }

      const content = fs.readFileSync(filePath, 'utf-8');

      if (!content.trim()) {
        Logger.warn(`Output file is empty: ${filePath}`);
        return null;
      }

      Logger.info(`Read output file (${content.length} bytes): ${filePath}`);
      return content;
    } catch (error) {
      Logger.error(
        `Failed to read output file: ${filePath}`,
        error instanceof Error ? error : undefined
      );
      return null;
    }
  }

  /**
   * Validate the output file content with basic Ruby syntax checks.
   * Returns true if the content looks like valid Ruby code.
   */
  validateContent(content: string): boolean {
    if (!content || !content.trim()) {
      Logger.warn('Output file content is empty');
      return false;
    }

    Logger.debug('Output file content validated');
    return true;
  }

  /**
   * Ensure the output directory exists, creating it if needed.
   */
  ensureOutputDirectory(): boolean {
    const filePath = this.getOutputFilePath();
    const dir = path.dirname(filePath);

    try {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
        Logger.info(`Created output directory: ${dir}`);
      }
      return true;
    } catch (error) {
      Logger.error(
        `Failed to create output directory: ${dir}`,
        error instanceof Error ? error : undefined
      );
      return false;
    }
  }

  /**
   * Clean up the output file (delete if exists).
   * Useful for ensuring a fresh state before execution.
   */
  cleanOutputFile(): boolean {
    const filePath = this.getOutputFilePath();

    try {
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        Logger.debug(`Cleaned output file: ${filePath}`);
      }
      return true;
    } catch (error) {
      Logger.error(
        `Failed to clean output file: ${filePath}`,
        error instanceof Error ? error : undefined
      );
      return false;
    }
  }

  /**
   * Set up a file watcher for the output file (for debugging purposes).
   * Returns a disposable that can be used to stop watching.
   */
  watchOutputFile(onChange: (content: string) => void): vscode.Disposable {
    const filePath = this.getOutputFilePath();
    const pattern = new vscode.RelativePattern(
      path.dirname(filePath),
      path.basename(filePath)
    );

    const watcher = vscode.workspace.createFileSystemWatcher(pattern);

    watcher.onDidChange(async () => {
      Logger.debug('Output file changed');
      const content = await this.readOutputFile();
      if (content) {
        onChange(content);
      }
    });

    watcher.onDidCreate(async () => {
      Logger.debug('Output file created');
      const content = await this.readOutputFile();
      if (content) {
        onChange(content);
      }
    });

    return watcher;
  }
}
